<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hati Mas Hari Ini</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Mengisi tinggi viewport */
            margin: 0; /* Menghilangkan margin default */
        }

        .heart {
            position: relative;
            width: 300px; /* Ukuran diperbesar 3 kali */
            height: 300px; /* Ukuran diperbesar 3 kali */
            background-color: red;
            transform: rotate(-45deg);
            animation: heartbeat 0.5s infinite;
        }

        .heart::before,
        .heart::after {
            content: "";
            position: absolute;
            width: 300px; /* Ukuran diperbesar 3 kali */
            height: 300px; /* Ukuran diperbesar 3 kali */
            background-color: red;
            border-radius: 50%;
        }

        .heart::before {
            top: -150px; /* Disesuaikan dengan ukuran baru */
            left: 0;
        }

        .heart::after {
            left: 150px; /* Disesuaikan dengan ukuran baru */
            top: 0;
        }

        @keyframes heartbeat {
            0%, 100% {
                transform: scale(1) rotate(-45deg);
            }
            50% {
                transform: scale(1.2) rotate(-45deg);
            }
        }
    </style>
</head>
<body>
    <div class="heart"></div>
</body>
</html>
